name: backpack
channels:
  - pytorch
  - defaults
dependencies:
  - pip=19.3.1
  - python=3.7.6
  - pip:
    - -r requirements.txt
    - -r requirements-dev.txt
    - -e .
    # Note: Enabling CUDA:
    # 1. CUDA Version: cat /usr/local/cuda/version.txt
    # 2. Find the command: https://pytorch.org/get-started/locally/
    # - pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
