repos:
- repo: https://github.com/psf/black
  rev: 21.4b0
  hooks:
  - id: black
    args: [--config=black.toml]
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.1'
  hooks:
  - id: flake8
    additional_dependencies: [
      mccabe,
      pycodestyle,
      pyflakes,
      pep8-naming,
      flake8-bugbear,
      flake8-comprehensions,
    ]
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.0.0
  hooks:
  - id: pydocstyle
    args:
    - --count
- repo: https://github.com/terrencepreilly/darglint
  rev: v1.8.0
  hooks:
  - id: darglint
    args:
    - --verbosity 2
